[versions]
agp = "8.10.0"
android-minSdk = "21"
android-compileSdk = "35"
android-buildToolsVersion = "35.0.0"
lib-version = "1.0.0"

kotlin = "2.1.21"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
